/*
 * SPDX-FileCopyrightText: 2026 Jolla Mobile Ltd
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef DNGLENSSHADING_H
#define DNGLENSSHADING_H

#include <QByteArray>
#include <QString>

// Builds a DNG OpcodeList1 payload (four GainMap opcodes, one per Bayer CFA
// phase: R, Gr, Gb, B) from a lens-shading calibration file generated by
// tools/calibration/generate_lens_shading.py.
//
// The calibration corrects both lens vignetting (all channels darkening
// towards the corners) and the associated color shift (channels darkening
// at different rates), since each CFA phase is corrected independently.
//
// Returns an empty QByteArray if no matching calibration is found, or if it
// does not apply to this camera/resolution/CFA combination -- callers should
// treat that as "no correction available" and continue without one.
namespace DngLensShading
{

// calibrationDir: directory containing lens_shading_camera<id>.json files
//                 (see tools/calibration/generate_lens_shading.py).
// cameraId:       Camera2 camera id the capture was taken with.
// cfaPattern:     "RGGB" / "GRBG" / "GBRG" / "BGGR", as already derived by
//                 the DNG writer for TIFFTAG_CFAPATTERN.
// width, height:  raw (mosaiced) image dimensions of the capture being
//                 written; must match the calibration's dimensions exactly.
QByteArray buildOpcodeList1(const QString &calibrationDir,
                            const QString &cameraId,
                            const QString &cfaPattern,
                            int width,
                            int height,
                            QString *warning);

}

#endif
